CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260111150207_InitialCreate') THEN
    CREATE TABLE "Notes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(500) NOT NULL,
        "Content" character varying(50000),
        "Pin" character varying(500),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Notes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260111150207_InitialCreate') THEN
    CREATE TABLE "UserCredentials" (
        code character varying(500) NOT NULL,
        matter character varying(50000),
        "secondaryPassword" text,
        "dateTimes" timestamp with time zone[] NOT NULL,
        CONSTRAINT "PK_UserCredentials" PRIMARY KEY (code)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260111150207_InitialCreate') THEN
    CREATE TABLE "NoteFiles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "NoteId" integer NOT NULL,
        "FileName" character varying(255) NOT NULL,
        "StoredFileName" character varying(255) NOT NULL,
        "FileType" character varying(50) NOT NULL,
        "ContentType" character varying(100) NOT NULL,
        "FileSize" bigint NOT NULL,
        "FileUrl" character varying(1000) NOT NULL,
        "PublicId" character varying(500) NOT NULL,
        "FilePath" character varying(500) NOT NULL,
        "UploadedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_NoteFiles" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_NoteFiles_Notes_NoteId" FOREIGN KEY ("NoteId") REFERENCES "Notes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260111150207_InitialCreate') THEN
    CREATE INDEX "IX_NoteFiles_NoteId" ON "NoteFiles" ("NoteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260111150207_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Notes_Code" ON "Notes" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260111150207_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_UserCredentials_code" ON "UserCredentials" (code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260111150207_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260111150207_InitialCreate', '9.0.2');
    END IF;
END $EF$;
COMMIT;

